### ISSUE TITLE
A plan for getting rid of LocalChannel special-casing

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#1448]
LocalProvider and AdHocProvider have special casing in them for LocalChannel.

This has resulted in broken code paths in LocalChannel (for example, execute_wait is broken, because it is not used in the special case - even though this method is the core method of a channel)

It has resulted in bugs in the non-special-case paths, because that code path is used less - for example #1318 

Based on some quick fixes I made for imsim, I propose eliminating the LocalChannel special-casing in `master`:

- [x] fix LocalProvider to work with remote channels properly:
  - [x] process killing is broken - PR #1447
  - [x] status checking is broken - PR #1449 
- [x] fix LocalProvider to not assume the Channel command line can be `bash` - specifically, LocalChannel execute_wait uses /bin/sh inside python `Popen` - PR #1452 
- [x] add a simple test for AdHocProvider - PR #1460 (this revealed brokenness somewhere which has been fixed)
- [x] fix LocalChannel to use new process groups for `execute_wait` like it does for `execute_no_wait` - PR #1461 
- [x] remove LocalProvider and AdHocProvider special casing for LocalChannel so that they are channel agnostic and the remote provider code-path is used for all channels  - PR #1471 
- [ ] remove now-unused `execute_no_wait` from all Channels - by this point, it is unused - PR #1629
