### ISSUE TITLE
Parsl 1.0.0 Release Checklist

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1692]
## Checklist

Please edit the checklist if I've missed any items. 

### Documentation updates :

- [x] Update docs to point at 1.0.0 as the latest
- [x] Make sure docs are not broken on readthedocs, since a broken doc build will stick on as stable till next release.
- [x] Update changelog with summary of changes since 0.9.0
- [x] Update Parsl tutorial repo with a 1.0.0 branch that folds in changes 
- [x] Add `Beta` tags to components/features that are not yet stable.

### Testing :

- [x] All testing should be green on Travis
- [x] Update all configs in `parsl/parsl/configs` to match current best practices
- [x] Update all test configs in `parsl/parsl/test/configs`
- [x] Test notebooks/tutorials and basic tests on a Mac

- [ ] Site testing:
  - [x] Comet (SDSC)
  - [x] Cori (NERSC)
  - [x] Stampede2 (TACC) (* tested with pre-alpha)
  - [x] Frontera (TACC) (* tested with pre-alpha)
  - [x] Theta (ALCF)
  - [ ] ~~Cooley (ALCF)~~
  - [x] Bluewaters (NCSA)
  - [ ] ~~Swan (Cray partner network)~~
  - [x] Summit (ORNL)
  - [x] CC-IN2P3 (French Grid)
  - [x] Midway (RCC, UChicago)
  - [ ] Open Science Grid
  - [x] AWS
  - [ ] ~~Azure~~
  - [ ] Kubernetes
  - [ ] Ad-Hoc clusters

### Release Tagging and pushing to PyPI

The Makefile now supports `make release` that covers the tagging, and push to pypi. We need to push an alpha quickly to smoothen the site specific testing.

An earlier version of this is available [here](https://gist.github.com/yadudoc/168ccdfe93d99d2e62548ce025e2afde) as a draft.

**Comment by danielskatz** [comment]
0.10.0 in a few places rather than 1.0.0?

**Comment by yadudoc** [comment]
@danielskatz I've updated the text to say 1.0.0 instead.
