### ISSUE TITLE
Parsl v1.1.0 Release Checklist

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#1979]
## Checklist

Please edit the checklist if I've missed any items. 

### Documentation updates :

- [x] Update docs to point at 1.1.0 as the latest
- [x] Make sure docs are not broken on readthedocs, since a broken doc build will stick on as stable till next release.
- [x] Update changelog with summary of changes since 0.9.0 [@benclifford to take a crack at this]
- [ ] Update Parsl tutorial repo with a 1.1.0 branch that folds in changes 
- [x] Add `Beta` tags to components/features that are not yet stable.

### Testing :

- [ ] All testing should be green on Travis
- [x] Update all configs in `parsl/parsl/configs` to match current best practices
- [x] Update all test configs in `parsl/parsl/test/configs`
- [x] Test notebooks/tutorials and basic tests on a Mac
- [ ] Post news update on the website about release

- [x] Site testing:
  - [x] Bridges2(PSC) [YY]
  - [ ] ~~Comet (SDSC)~~ Machine is getting replaced by Expanse
  - [x] Cori (NERSC) [YY/Yadu]
  - [x] Stampede2 (TACC) [Yadu]
  - [ ] ~~Frontera (TACC)~~ [Yadu, no access]
  - [x] Theta (ALCF) [YY]
  - [x] Bluewaters (NCSA) [ZZ]
  - [x] Summit (ORNL) [Yadu]
  - [ ] ~~CC-IN2P3 (French Grid)~~ [Yadu]
  - [x] Midway (RCC, UChicago) [YY]
  - [x] Open Science Grid
  - [x] AWS
  - [x] Kubernetes [ZZ]
  - [x] NSCC Singapore [ZZ]
  - [ ] Ad-Hoc clusters [YY]

### Release Tagging and pushing to PyPI

I'll make an updated alpha to smoothen installation and site testing.

**Comment by danielskatz** [comment]
ponentially

- [ ] add names of new contributors to codemeta file
- [ ] create new archive on zenodo (may be done automatically) and list DOI of archive in docs/website

**Comment by yongyanrao** [comment]
For the test on theta, noticed a version issue, as reported here.
https://github.com/Parsl/parsl/issues/1990

**Comment by yongyanrao** [comment]
For parsl site tests
1. midway
configs worked, needed to make changes in `parsl/tests/site_tests/conda_setup.sh` file
```
module load python/anaconda-2020.02
source /software/python-anaconda-2020.02-el7-x86_64/bin/activate
```

**Comment by yongyanrao** [comment]
For site test on bridges2@psc, all tests passed.
- in `parsl/tests/configs/local_user_opts.py`, needed to add items of `'partition'` and `'scheduler_options'`

**Comment by yongyanrao** [comment]
For site test on stampede2@tacc, all tests passed.
- needed to add `stampede2.py` in `parsl/tests/configs/`, we can just use `frontera.py` as a template
- in parsl/tests/configs/local_user_opts.py, needed to add an item for `'stampede2'`

**Comment by ZhuozhaoLi** [comment]
NSCC site tests passed with the config in #2003

**Comment by yadudoc** [comment]
@benclifford  Could you update the changelog with join_app and other changes that have gone in. I'll push a branch with the changelog template updated for 1.1.0.

**Comment by danielskatz** [comment]
👋 @benclifford - ping...

**Comment by benclifford** [comment]
I've updated the changelog with info on joinapp and on other changes that I made since 1.0.0

**Comment by yadudoc** [comment]
I've just finished testing on OSG, AWS, and Summit. I'll call site-testing done at this point.
