### ISSUE TITLE
Towards type-checking dfk.__init__

### ISSUE THREAD

**Issue by benclifford** [Parsl/parsl#2540]
On the benc-mypy branch, I ended up with dfk.__init__ being type-checked. This is important as a step towards the whole DFK class being type checked, which is important as being one of the core classes of parsl.

This requires some prerequisite untangling, which I have separated out into several patches, and which I will merge as separate PRs.

These are detailed below.

Some untangling comes from the vagueness of when/which executors should be scaled:
- [x] #2537 removes the `executor.managed` property, and with it the vague notion of managed vs unmanaged executors
- [x] #2545 executor.scaling_enabled is a further flag that indicates whether scaling should happen. In line with #2539 this should go away.
- [x] #2544 #2543 #2542 several explicit type annotations are needed to help `mypy` infer the full types of attributes initialised to `None` - this is basically a technical limitation of python static type checking.
- [x] #2551 the DFK code is vague about whether app argument lists are lists or tuples, and some code moves between both of those formats. There is already some code to treat app arguments as Sequences, which accomodates both, and some more tidyup needs to happen here.
- [x] #2541 checkpoint configuration for timers needs some tidying up to make it type check, and at the same time I will take the opportunity to make it raise a configuration error rather than fairly quietly continue if it cannot parse a duration, as a usability enhancement
- [ ] finally typeguard can be enabled on dfk.__init__ and type annotations can be added to dfk.__init__. This turns on typechecking at runtime for dfk.__init__, as well as propagating types of the various DFK attributes throughout parsl, whenever an already type-checked function makes reference to a DFK.
