### ISSUE TITLE
Usage Tracking and logging for Parsl project reporting

### ISSUE THREAD

**Issue by yadudoc** [Parsl/parsl#34]
For reporting purposes we need to capture the following information

 - [ ] Hash of Username, hostname (ip) 
 - [ ] Hash of Parsl script (if possible)
 - [ ] Count of apps launched by DFK
 - [ ] Site IDs used
 - [ ] Total run time

A UDP packet with this info could be sent out from the Parsl script and this could be captured and logged on a server hosted on AWS.
Here are the components we'll need
 - [ ] Log info on the client side and send a UDP packet
 - [ ] Receive and log info to stable storage on our side.
 - [ ] Config option to opt-out of tracking
 - [ ] Documentation to clearly indicate the info collected and how to opt-out

**Comment by kylechard** [comment]
At this stage we should focus on the bare minimum (and least invasive). 

Some of these stats can be sent at the beginning while others are sent at the end. Sending at the end is slightly risky as there might be failures that would kill the script.  

Begininig
- [ ] hash of username+IP (to avoid the millions of 'ubuntu' users)
- [ ] UDP packet will include sending IP
- [ ] start time

End
- [ ] number of apps launched by DFK
- [ ] number of app failures
- [ ] number of sites used
- [ ] total compute hours
- [ ] end time

In the future we could add the following
- [ ] site ID (when we have a site registry)
- [ ] hash of the script

**Comment by annawoodard** [comment]
We might also consider a username-based filter for devs, which would automatically set a flag to lump testing stats separately from user stats. Presumably for project reporting we only want user stats, and it could be a pain to disentangle them post hoc. Alternatively we could have a 'testing mode' configuration flag, but that makes it more likely we forget to set it sometimes and inflate the user stats.

**Comment by kylechard** [comment]
Agreed. We actually discussed this same topic this afternoon. The thought was to have a testing mode for our usage and for our automated tests.

**Comment by annawoodard** [comment]
Sounds good! Were you guys thinking a testing mode configuration flag, or an automated filter? Everyone makes mistakes, so if we let it be possible for us to forget, I think we will forget from time to time.

Filter pros:
1) Eliminates per-workflow possibility dev forgets to set the flag

Filter cons:
1) Introduces per-dev possibility we forget to add dev to the filter
2) Possible collisions (user gets filtered as dev)-- probably unlikely for now
3) Less flexible: there may be situations where devs should count as users
4) More work for new people to contribute

OK, maybe I'm overthinking this, but maybe filter+config flag is the way to go. In other words, if the config flag is not set, the default would be to evaluate the filter (so devs would by default run in testing mode). But the configuration flag would override that so that a dev could run in user mode, or a user could run in testing mode. That would eliminate cons 3) and 4).

**Comment by yadudoc** [comment]
I am in the process of adding is a testing mode where the usage stats would contain a test flag so that we can identify them and tell apart the origin. For automated tests, I'll be setting this flag.

I agree that the tests should not be counted and there's a possibility that we might forget the flag while developing tests. There's little risk here since these would be short and we generally don't count scripts that run shorter than a minute. If necessary, we could also track the filename and exclude one's that start with test_ which is a convention we follow for all our tests.

**Comment by annawoodard** [comment]
> There's little risk here since these would be short and we generally don't count scripts that run shorter than a minute.

I'm definitely planning on testing with more realistic workflows that would run longer than a minute 😄 .

I'm fine with scrapping the username filter idea, but I would emphatically protest filtering on filenames. A lot of users consider the first time they run something to be a 'test' and will have files named "test_v10" and "test_v1_new_reallynew_v1_v2_latest" etc.

**Comment by yadudoc** [comment]
With this functionality merged, I think this issue should be closed and we should open a doc issue on documenting anonymized usage tracking and being upfront about it.
